export const POSTS = [
  {
    _id: "1",
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: "/posts/post1.png",
    user: {
      username: "lukeskywalker",
      profileImg: "https://robohash.org/lukeskywalker?set=set4",
      fullName: "Luke Skywalker",
    },
    comments: [
      {
        _id: "1",
        text: "Nice Tutorial",
        user: {
          username: "princessleia",
          profileImg: "https://robohash.org/princessleia?set=set4",
          fullName: "Princess Leia",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "2",
    text: "How you guys doing? 😊",
    user: {
      username: "anakinskywalker",
      profileImg: "https://robohash.org/anakinskywalker?set=set4",
      fullName: "Anakin Skywalker",
    },
    comments: [
      {
        _id: "1",
        text: "Nice :)",
        user: {
          username: "princessleia",
          profileImg: "https://robohash.org/princessleia?set=set4",
          fullName: "Princess Leia",
        },
      },
    ],
    likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
  },
  {
    _id: "3",
    text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
    img: "/posts/post2.png",
    user: {
      username: "darthvader",
      profileImg: "https://robohash.org/darthvader?set=set4",
      fullName: "Darth Vader",
    },
    comments: [],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
    ],
  },
  {
    _id: "4",
    text: "I'm learning GO this week. Any tips? 🤔",
    img: "/posts/post3.png",
    user: {
      username: "princessleia",
      profileImg: "https://robohash.org/princessleia?set=set4",
      fullName: "Princess Leia",
    },
    comments: [
      {
        _id: "1",
        text: "youtube tutorials are the best",
        user: {
          username: "anakinskywalker",
          profileImg: "https://robohash.org/anakinskywalker?set=set4",
          fullName: "Anakin Skywalker",
        },
      },
    ],
    likes: [
      "6658s891",
      "6658s892",
      "6658s893",
      "6658s894",
      "6658s895",
      "6658s896",
      "6658s897",
      "6658s898",
      "6658s899",
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: "1",
    fullName: "Darth Vader",
    username: "darthvader",
    profileImg: "https://robohash.org/darthvader?set=set4",
  },
  {
    _id: "2",
    fullName: "Luke Skywalker",
    username: "lukeskywalker",
    profileImg: "https://robohash.org/lukeskywalker?set=set4",
  },
  {
    _id: "3",
    fullName: "Anakin Skywalker",
    username: "anakinskywalker",
    profileImg: "https://robohash.org/anakinskywalker?set=set4",
  },
  {
    _id: "4",
    fullName: "Princess Leia",
    username: "princessleia",
    profileImg: "https://robohash.org/princessleia?set=set4",
  },
];
